// <auto-generated />
using KPZ_Lab_6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KPZ_Lab_6.Migrations
{
    [DbContext(typeof(PracticeContext))]
    partial class PracticeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KPZ_Lab_6.Models.Department", b =>
                {
                    b.Property<string>("DeptNo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("dept_no")
                        .IsFixedLength(true);

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("location");

                    b.HasKey("DeptNo")
                        .HasName("PK_DEP_Department");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("KPZ_Lab_6.Models.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<string>("DeptNo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("dept_no")
                        .IsFixedLength(true);

                    b.Property<string>("EmpFname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("emp_fname");

                    b.Property<string>("EmpLname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("emp_lname");

                    b.HasKey("EmpNo")
                        .HasName("PK__Employee__129850FA0C0A47DE");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("KPZ_Lab_6.Models.MigrationDemo", b =>
                {
                    b.Property<string>("MigrationNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MigrationDemoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MigrationNum");

                    b.ToTable("MirarionDemos");
                });

            modelBuilder.Entity("KPZ_Lab_6.Models.Project", b =>
                {
                    b.Property<string>("ProjectNo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("project_no")
                        .IsFixedLength(true);

                    b.Property<long>("Budget")
                        .HasColumnType("bigint")
                        .HasColumnName("budget");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("project_name");

                    b.HasKey("ProjectNo")
                        .HasName("PK__Project__BC79D7FB7EA6F4C7");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("KPZ_Lab_6.Models.Employee", b =>
                {
                    b.HasOne("KPZ_Lab_6.Models.Department", "DeptNoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .HasConstraintName("FK__Employee__dept_n__267ABA7A")
                        .IsRequired();

                    b.Navigation("DeptNoNavigation");
                });

            modelBuilder.Entity("KPZ_Lab_6.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
